Feat game config
klkelley/tictactoe-clojure pull request #2
Opened 2018-02-14 15:49 UTC by klkelley

https://trello.com/c/FFUT5aqJ/50-425-game-configuration-menu

2018-02-15 15:10 UTC, andarcabrera reviewed
It's not in the diff, but you can delete the core test that was part of the original setup.

2018-02-15 15:10 UTC, andarcabrera commented on src/tictactoe/game_runner.clj
> +  (let [game-options (game-menu/menu game-types board-sizes)]
is the `let` necessary here? can you call the function directly?

2018-02-15 15:10 UTC, andarcabrera commented on src/tictactoe/game_menu.clj
> +(defn pick-board-size [board-sizes]
`pick-game` and `pick-board-size` functions seem identical except the parameter that's passed in and the message. Can that be abstracted?

2018-02-15 15:10 UTC, andarcabrera commented on src/tictactoe/game_menu.clj
> +(defn pick-player-two-marker [player1-marker]
same for the `pick-player-marker`. Can you use an optional argument and abstract this function?

2018-02-15 15:48 UTC, aaronlahey requested changes

2018-02-15 15:48 UTC, aaronlahey commented on project.clj
> +  :plugins [[lein-cloverage "1.0.10"] [lein-eftest "0.4.3"]]
👍

2018-02-15 15:48 UTC, aaronlahey commented on test/tictactoe/game_menu_test.clj
> +  (:require [clojure.test :refer :all]
`:refer :all` is a bad practice in most cases. I basically *always* prefer `:as`.

`:as` > `:refer [a b c]` > `:refer :all` > `:use`

2018-02-15 15:48 UTC, aaronlahey commented on test/tictactoe/game_menu_test.clj
> +	 (with-out-str "test" (ui/print-message (messages/player-two-marker))
Some strange formatting here. and below. If you're in vim, a lot of times I'll just select the whole file and press `=` to reformat.

2018-02-15 15:48 UTC, aaronlahey commented on test/tictactoe/game_menu_test.clj
> +	 (with-out-str "test" (ui/print-message (messages/player-two-marker))
`gg` go to top
`V` to select the first line
`G` to select all lines
`=` to reindent

2018-02-15 15:48 UTC, aaronlahey commented on test/tictactoe/game_runner_test.clj
> +  (apply str (interleave coll (repeat "\n"))))
`interpose` over `interleave` here.

2018-02-15 15:48 UTC, aaronlahey commented on src/tictactoe/user_interface.clj
> +(defn loop-and-print [options]
Can you format your functions like this...

```
(defn do-something
  []
  (println "hi"))
```

2018-02-15 15:48 UTC, aaronlahey commented on src/tictactoe/marker_validation.clj
> +	(:require [tictactoe.user-interface :as ui]
Formatting? I'm going to start cracking down on wat formatting. When you put your PRs up just glance over them and look for formatting issues. Ideally, when you join a team, you'll have a tool which lints the code if not auto format it for you.

2018-02-15 15:48 UTC, aaronlahey commented on src/tictactoe/marker_validation.clj
> +(ns tictactoe.marker-validation
I feel like there are already too many namespaces for the amount of functionality you've implemented. There isn't really a 1-1 correspondence between namespaces and classes in Java and I feel like that's where you're headed.

Let's try this. Implement everything in a single namespace for now and when it becomes painful, or responsibilities start to become muddled we'll extract namespaces.

2018-02-15 15:48 UTC, aaronlahey commented on test/tictactoe/user_interface_test.clj
> +  (with-out-str "test"
Formatting.

2018-02-16 00:43 UTC, aaronlahey requested changes

2018-02-16 00:43 UTC, aaronlahey commented on src/tictactoe/game_runner.clj
> +    It displays the summary of options and returns a hash-map of choices."
Strange indentation here. You'll want to indent your docstrings so when you call `(doc tictactoe.game-runner/menu)` at the repl it looks correctly formatted.

That's usually like this

```
(defn add
  "Returns the sum of two number. Oh look,
  a newline!"
  [x y]
  (+ x y))

2018-02-16 00:43 UTC, aaronlahey commented on test/tictactoe/game_runner_test.clj
> +    (is (= "Invalid. Please pick an available option.\n"
You might want to check your indentation settings. Generally *most* functions should align arguments like this:

```
(is (= 42
       (+ 21 21)))
```

Certain Clojure functions just indent two spaces without aligning. I would expect `with-*`, `def*`, etc to be that way.

2018-02-16 00:43 UTC, aaronlahey commented on test/tictactoe/game_runner_test.clj
> +  (with-out-str "test" (with-in-str (make-input '("1" "2" "a" "b")) (game-runner/start))))
When I'm reading these tests all I can really see is `with-out-str` and `with-in-str`. Is there a way to refactor so the tests more clearly reveal what exactly they're testing?

2018-02-16 00:43 UTC, aaronlahey commented on src/tictactoe/game_runner.clj
> +  (set (.split "abcdefghijklmnopqrstuvwxyz" "")))
See if you can do this without using Java interop.

2018-02-16 00:47 UTC, aaronlahey commented
Ugh. I submitted my review before writing my final comment:

So as the code stand now there are two namespaces:

```
tictactoe.main
tictactoe.game-runner
```

`tictactoe.main` is the entry point to your *whole* program. It invokes `tictactoe.game-runner/start`. That suggests that you have a single public function to export/test, yet I see a handful of functions with docstrings and dedicated unit tests. You're creating a tighter coupling between your production code and your unit tests than needs to exist.

Since there's only one function which is being used outside of `game-runner` (`start`) lets declare every other function as private:

2018-02-16 00:59 UTC, aaronlahey commented
I also get test failures when I run `lein test` locally. Can you confirm your CI is working correctly?

2018-02-16 16:32 UTC, merged